import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppShell } from "@/components/app-shell";
import { RouteTransition } from "@/components/route-transition";
import { Toaster } from "@/components/ui/sonner";
import { QueryProvider } from "@/lib/query-provider";
import { HealthCheckProvider } from "@/lib/health-provider";
import { BackendGuard } from "@/components/backend-guard";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        <QueryProvider>
          <HealthCheckProvider>
            <AppShell>
              <BackendGuard>
                <RouteTransition>{children}</RouteTransition>
              </BackendGuard>
            </AppShell>
            <Toaster />
          </HealthCheckProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
